// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5wDMISBF8G1HzWvjjkVZdUJySWB0_HkU',
    appId: '1:806797008186:web:c81d3172da6ce391b90403',
    messagingSenderId: '806797008186',
    projectId: 'social-media-app-3e57c',
    authDomain: 'social-media-app-3e57c.firebaseapp.com',
    storageBucket: 'social-media-app-3e57c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnn-2TmmEv1pN-3vfK8DKf54ZBIRdoJ7s',
    appId: '1:806797008186:android:f2c4f669dec97f9bb90403',
    messagingSenderId: '806797008186',
    projectId: 'social-media-app-3e57c',
    storageBucket: 'social-media-app-3e57c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBCP2OP3bu1sgZ393JOZLd0fEDYyLIYtQ',
    appId: '1:806797008186:ios:f0591cb313afc7e0b90403',
    messagingSenderId: '806797008186',
    projectId: 'social-media-app-3e57c',
    storageBucket: 'social-media-app-3e57c.appspot.com',
    iosClientId: '806797008186-avng4a7prk4e8emg9a2afv1o108tv1fj.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBCP2OP3bu1sgZ393JOZLd0fEDYyLIYtQ',
    appId: '1:806797008186:ios:f0591cb313afc7e0b90403',
    messagingSenderId: '806797008186',
    projectId: 'social-media-app-3e57c',
    storageBucket: 'social-media-app-3e57c.appspot.com',
    iosClientId: '806797008186-avng4a7prk4e8emg9a2afv1o108tv1fj.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
